"""Regression cases A–F + addendum: every scenario JSON validates and meets its expectations under the
analytical fallback simulator (≥200 trials). The Controller-based simulator plugs into the same
``run(..., simulate_fn=...)`` slot once it lands (see ``expectations.controller`` for what it must check)."""
from __future__ import annotations

import json
from functools import partial
from pathlib import Path

import pytest

from sonnet_orchestrator.diagnostics.montecarlo import check_expectations, run, simple_simulate
from sonnet_orchestrator.diagnostics.scenarios import SCENARIOS, SCENARIO_FIXTURES_DIR, Scenario, build

TRIALS = 200
SEED = 20260914
EXPECTED_NAMES = {
    "case-A-writer-down-mid-poem", "case-B-race-same-index", "case-C-delayed-receipt", "case-D-stale-version-storm",
    "case-E-lead-only-letter-parity-trap", "case-F-final-word-single-publisher",
    "nohitori-entry1-94min", "nohitori-entry2-6h43m", "consent-lag", "frame-churn", "mass-applicant", "self-offer",
    "stale-offer", "dual-table", "silent-writer", "58-59-cover-trap", "96-97-beg-trap", "hybrid-plan",
    "pre-roster-403", "2000-char-table", "team-plan-leak",
}
FILES = sorted(SCENARIO_FIXTURES_DIR.glob("*.json"))


def _load(p: Path) -> Scenario:
    return Scenario.from_dict(json.loads(p.read_text(encoding="utf-8")))


def test_all_scenarios_present():
    assert set(SCENARIOS) == EXPECTED_NAMES
    assert {p.stem for p in FILES} == EXPECTED_NAMES


@pytest.mark.parametrize("path", FILES, ids=[p.stem for p in FILES])
def test_scenario_schema(path):
    d = json.loads(path.read_text(encoding="utf-8"))
    assert d["schema"] == 1 and d["name"] == path.stem
    sc = _load(path)
    assert sc.validate() == []
    assert sc.to_dict() == d
    for w in sc.writers:
        assert w.letter_set()
    # JSON must match the builder (fixtures are generated by dump_all)
    assert build(sc.name).to_dict() == d


@pytest.mark.parametrize("path", FILES, ids=[p.stem for p in FILES])
def test_scenario_expectations(path, settings):
    sc = _load(path)
    need_surv = "single_failure_survivability_min" in sc.expectations
    rep = run(sc, TRIALS, SEED, partial(simple_simulate, settings=settings), survivability=need_surv)
    assert rep.trials == TRIALS
    bad = check_expectations(rep, sc.expectations)
    assert not bad, f"{sc.name}: {bad}; report={rep.as_dict()}"


def test_replay_derived_scenarios_carry_real_evidence():
    e1 = _load(SCENARIO_FIXTURES_DIR / "nohitori-entry1-94min.json")
    e2 = _load(SCENARIO_FIXTURES_DIR / "nohitori-entry2-6h43m.json")
    assert round(e1.evidence["minutes_to_complete"]) == 94 and len(e1.words) == 125
    assert round(e2.evidence["minutes_to_complete"]) == 403 and len(e2.words) == 131
    assert e2.evidence["contributions"] == {"VxSdDkhu": 43, "W4TAejK6": 41, "f9vthSUn": 28, "F6jvabi2": 19}
    assert all(w.did.startswith("did:key:") for w in e1.writers + e2.writers)
    beg = _load(SCENARIO_FIXTURES_DIR / "96-97-beg-trap.json")
    assert beg.evidence["96"]["word"] == "dead" and beg.evidence["97"]["word"] == "ask"
    assert sorted(d[-8:] for d in beg.evidence["97"]["spellers"]) == ["W4TAejK6", "f9vthSUn"]
    assert beg.words[96] == "beg"
    cover = _load(SCENARIO_FIXTURES_DIR / "58-59-cover-trap.json")
    assert cover.evidence["entry1_58_59"]["58"]["word"] == "more."
    assert cover.evidence["entry1_58_59"]["59"]["word"] == "Some"
    assert cover.evidence["nohitori2_words_at_58_59"]["58"]["word"] == "if"
    assert cover.evidence["nohitori2_equivalent_56_57"]["57"]["word"] == "then"
    assert cover.words[58] == "The"
